interface SystemArr {
  mark: string
  isSenior: boolean
  isDeputy: boolean
  isSelect: boolean
  haveItem: string[]
  value: string
}
const setUpTypeData: SystemArr[] = [
  {
    mark: 'LFS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP08398913',
  },
  {
    mark: 'OCT',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP90838309',
  },
  {
    mark: 'XFS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP990000009',
  },
  {
    mark: 'AS3S',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP70932487',
  },
  {
    mark: 'S3-CS',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP90838399',
  },
  {
    mark: 'S3-OSS',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP938572619',
  },
  {
    mark: 'MABS',
    isSenior: false,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '3'],
    value: 'HSP093852758',
  },
  {
    mark: 'MADLG',
    isSenior: false,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '3'],
    value: 'HSP093852759',
  },
  // {
  //     mark: 'OEOS1OS',
  //     isSenior: true,
  //     isDeputy: true,
  //     isSelect: false,
  //     haveItem: ["1", "2", "3"],
  //     value:"HSP08934870"
  // },
  {
    mark: 'HCP',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP08934870',
  },
  {
    mark: 'MQE',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP43252839',
  },
  // {
  //     mark: 'HCP-CS',
  //     isSenior: false,
  //     isDeputy: true,
  //     isSelect: false,
  //     haveItem: ["1", "3"],
  //     value:"HSP08398913"
  // },
  {
    mark: 'OS',
    isSenior: true,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '2', '3'],
    value: 'HSP08934877',
  },
  {
    mark: 'BBCS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP746284938',
  },
  {
    mark: 'FTP',
    isSenior: true,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1', '2'],
    value: 'HSP03858729',
  },
  {
    mark: 'SFTP',
    isSenior: true,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1', '2'],
    value: 'HSP03858730',
  },
  // {
  //     mark: 'TFTP',
  //     isSenior: true,
  //     isDeputy: false,
  //     isSelect: false,
  //     haveItem: ["1", "2"],
  //     value:"HSP08398913"
  // },
  {
    mark: 'CIFS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP019811212',
  },
  {
    mark: 'NFS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP019850801',
  },
  // {
  //     mark: 'HDFS',
  //     isSenior: true,
  //     isDeputy: false,
  //     isSelect: false,
  //     haveItem: ["1", "2"],
  //     value:"HSP019850801"
  // },
  {
    mark: 'WEBDAV',
    isSenior: false,
    isDeputy: true,
    isSelect: false,
    haveItem: ['1', '3'],
    value: 'HSP957369395',
  },
  {
    mark: 'MFS',
    isSenior: false,
    isDeputy: false,
    isSelect: false,
    haveItem: ['1'],
    value: 'HSP53467290',
  },
]

type FileDataList<T, U> = Array<{
  mark: string
  value: string
  icon: string
  isSelect: boolean
  data: T
  seniorData: U
}>
// 左侧列表数据
const fileData: FileDataList = [
  {
    mark: '10.0.11.12LFS',
    value: 'LFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '3344',
      view: '2',
      tableData: [],
      remark: '56677',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.123AS3S',
    value: 'AS3S',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '244455',
      accountType: '',
      area: '',
      remark: '55555',
      visitKey: '',
      passwordKey: '',
      buckect: '',
      isTLS_visit: false,
      isAll: false,
      isTLS_book: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1231XFS',
    value: 'XFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '224455322334455',
      testType: '1',
      usermark: '',
      remark: '4566',
      password: '',
      host: '2334',
      port: '223',
      catalog: '',
      isAnonymous: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.11CS',
    value: 'S3-CS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '',
      sign: '',
      host: '',
      remark: '',
      visitKey: '',
      passwordKey: '2233',
      buckect: '',
      isTLS_visit: false,
      isTLS_book: true,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112OSS',
    value: 'S3-OSS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '34455',
      sign: '',
      serverOffer: '',
      remark: '',
      visitKey: '',
      passwordKey: '2233',
      buckect: '',
      isTLS_visit: false,
      isTLS_book: true,
      systemEnterType: '',
      area: '',
      host: '',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112MABS',
    value: 'MABS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'MABS',
      testType: '1',
      remark: '',
      serverUrl: '2233444444444444444',
      serverType: '3',
      password: '1444',
      usermark: '13444',
      isTLS_visit: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112OEOS1OS',
    value: 'OEOS1OS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'OEOS1OS',
      edition: '',
      remark: '',
      tenantID: '',
      domain: '333',
      spacemark: '3344',
      approve: '',
      base64mark: '2355',
      MD5: '2233',
      isTLS_visit: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112MQE',
    value: 'MQE',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'MQE',
      HCP_enter: '2334',
      remark: '333',
      queryType: '3',
      queryScript: '3',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112HCP-CS',
    value: 'HCP-CS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'HCP-CS',
      host: '344',
      remark: '',
      sign: '',
      visitKey: '',
      passwordKey: '',
      buckect: '',
      isTLS_visit: true,
      isTLS_book: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112OS',
    value: 'OS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'OS',
      host: '344',
      remark: '',
      sign: '',
      visitKey: '',
      passwordKey: '',
      buckect: '',
      isTLS_visit: false,
      isTLS_book: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112BBCS',
    value: 'BBCS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: '344',
      loginID: '',
      remark: '5',
      loginPassword: '444',
      buckect: '',
      isTLS_visit: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112FTP',
    value: 'FTP',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'FTP',
      host: '334',
      port: '',
      catalog: '',
      usermark: '',
      password: '',
      encryptionTransmission: '1',
      remark: '',
    },
    seniorData: {
      isMonitor: true,
      isUTF_8: false,
      code: '',
      transer: '',
      catalog: '',
      fileType: '',
      space: 0,
      linkNum: 0,
      order: '',
      loginUser: '',
    },
  },
  {
    mark: '10.0.11.1112HDFS',
    value: 'HDFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'HDFS',
      host: '334233',
      port: '',
      catalog: '',
      usermark: '',
      password: '',
      encryptionTransmission: '', // 配合定义接口
      remark: '',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112SFTP',
    value: 'SFTP',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'SFTP',
      host: '34556',
      port: '',
      catalog: '555',
      usermark: '',
      password: '',
      remark: '555',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112TFTP',
    value: 'TFTP',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'TFTP',
      host: '23344',
      port: '',
      catalog: '334',
      remark: '333',
    },
    seniorData: {
      codeType: '33',
      transType: '3',
      timeout: 230,
    },
  },
  {
    mark: '10.0.11.1112CIFS',
    value: 'CIFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'CIFS',
      host: '34',
      sharemark: '22',
      usermark: '',
      password: '',
      remark: '',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112NFS',
    value: 'NFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'NFS',
      host: '333',
      sharemark: '33',
      usermark: '2',
      password: '2',
      GID: 10,
      UID: 50,
      remark: '',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112WEBDAV',
    value: 'WEBDAV',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'WEBDAV',
      host: '33434',
      usermark: '444',
      password: '',
      catalog: '',
      remark: '2233',
      isTLS_visit: true,
      isTLS_book: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112MFS',
    value: 'MFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'MFS',
      storage: 10,
      unit: 'GB',
      remark: '22222',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112MFS111',
    value: 'MFS11',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'MFS',
      storage: 10,
      unit: 'GB',
      remark: '22222',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112VFS',
    value: 'VFS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'VFS',
      storage: 10,
      unit: 'GB',
      remark: '22222',
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112HMS',
    value: 'HMS',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'HMS',
      roll: '',
      remark: '',
      server: '',
      password: '',
      usermark: '',
      isTLS_visit: true,
      isTLS_book: false,
    },
    seniorData: null,
  },
  {
    mark: '10.0.11.1112TIKV',
    value: 'TIKV',
    icon: 'icon_1.png',
    isSelect: false,
    data: {
      mark: 'TIKV',
      host: '34444',
      port: '',
      prefix: '',
      limit: 10,
      client: '1',
      remark: '',
    },
    seniorData: null,
  },
]
export { setUpTypeData, fileData }
